[package]
name = "gpu"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
env_logger = "0.11.8"
ash = "0.38.0"

[build-dependencies]
spirv-builder = { git = "https://github.com/Rust-GPU/rust-gpu", rev = "698f10ac14b7c952394ac5620004e4e973308902" }
