[package]
name = "dsp"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde_json = "1.0.140"
serde = { version = "1.0", features = ["derive"] }
axum = "0.8.3"
tracing-subscriber = "0.3.19"
